name: Deploy Flutter Web to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter create --platforms=web --project-name turneo .
      - run: flutter pub get
      - name: Analyze
        continue-on-error: true
        run: flutter analyze
      - name: Build web
        env:
          SUPABASE_URL: https://iiaxbriosudkmhsqvksn.supabase.co
          SUPABASE_PUBLISHABLE_KEY: ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: flutter build web --release --base-href "/TURNEO-Flutter/" --dart-define=SUPABASE_URL="$SUPABASE_URL" --dart-define=SUPABASE_PUBLISHABLE_KEY="$SUPABASE_PUBLISHABLE_KEY" --dart-define=SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY"
      - uses: actions/configure-pages@v5
        with:
          enablement: true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
